name: rid python package test

on:
  - push
  - pull_request

jobs:
  Unittest:
    runs-on: ubuntu-latest
    container:
      image: pkufjhdocker/rid-test:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unittest
      run: |
        pip install pydflow
        cd ./tests
        coverage run -m unittest discover op
        DFLOW_DEBUG=1 coverage run -m unittest