name: rid python package test

on:
  - push
  - pull_request

jobs:
  Unittest:
    runs-on: ubuntu-latest
    container:
      image: pkufjhdocker/rid-kit:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unittest
      run: |
        cd ./tests
        python -m unittest